[package]
name = "Mystem"

[dependencies]
MoveStdlib = { git = "https://github.com/gonative-cc/dwallet-network", subdir = "crates/sui-framework/packages/move-stdlib", rev = "develop" }
dWallet = { git = "https://github.com/gonative-cc/dwallet-network", subdir = "crates/sui-framework/packages/dwallet-framework", rev = "develop" }
[addresses]
mystem = "0x2"
